services:
  notifyservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: notifyservice:0.1.0
    env_file:
      - .env
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/api/v1/notify/health/ready || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - notifyservice_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:8-alpine
    command: >
      redis-server
      --appendonly no
      --save ""
      --maxmemory-policy noeviction
      --tcp-keepalive 60
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - notifyservice_net

networks:
  notifyservice_net:
    driver: bridge
